/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.oms.view;

import edu.ijse.oms.connector.ServerConnection;
import edu.ijse.oms.controller.KitchenOrderController;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Randula
 */
public class AdminConsol extends javax.swing.JFrame {

    /**
     * Creates new form AdminConsol
     */
    public AdminConsol() {
        initComponents();
    }

    AdminConsol(String userId, String userName) {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        OperatorReport = new javax.swing.JButton();
        btnChefSummery = new javax.swing.JButton();
        ChefReport = new javax.swing.JButton();
        cmbDate = new org.jdesktop.swingx.JXDatePicker();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(102, 0, 0));
        lblTitle.setText("Admin View...");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 270, 46));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OperatorReport.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        OperatorReport.setForeground(new java.awt.Color(153, 51, 0));
        OperatorReport.setText("Telephone Operators Report");
        jPanel1.add(OperatorReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 290, 80));

        btnChefSummery.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnChefSummery.setForeground(new java.awt.Color(153, 51, 0));
        btnChefSummery.setText("Chefs' Summery");
        btnChefSummery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChefSummeryActionPerformed(evt);
            }
        });
        jPanel1.add(btnChefSummery, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 290, 80));

        ChefReport.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ChefReport.setForeground(new java.awt.Color(153, 51, 0));
        ChefReport.setText("Chefs Report");
        jPanel1.add(ChefReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 290, 80));
        jPanel1.add(cmbDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 160, 40));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChefSummeryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChefSummeryActionPerformed
        try {
            Date date = cmbDate.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String searchDate = sdf.format(date);

            String chefId = txtId.getText();
            KitchenOrderController kitchenOrderController = ServerConnection.getServerConnector().getKitchenOrderController();
            String[] summeryList = kitchenOrderController.getSummeryList(searchDate, chefId);

            JasperPrint jp = null;
            JasperReport jr = JasperCompileManager.compileReport("./src/report/ChefsSummery.jrxml");

            Map hm = new HashMap();
            hm.put("name", summeryList[0]);
            hm.put("noOfOrders", summeryList[1]);
            hm.put("qty", summeryList[2]);
            hm.put("totalTime", summeryList[3]);
            
            System.out.println("Hash Map  "+hm);
            
             jp = JasperFillManager.fillReport(jr, hm, new JREmptyDataSource());
            JasperViewer.viewReport(jp, false);
            
        } catch (IOException | NotBoundException | ParseException | JRException ex) {
            Logger.getLogger(AdminConsol.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnChefSummeryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminConsol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminConsol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminConsol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminConsol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminConsol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChefReport;
    private javax.swing.JButton OperatorReport;
    private javax.swing.JButton btnChefSummery;
    private org.jdesktop.swingx.JXDatePicker cmbDate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
