/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.oms.view;

import edu.ijse.oms.connector.ServerConnection;
import edu.ijse.oms.controller.UserController;
import edu.ijse.oms.model.User;
import java.io.IOException;
import java.rmi.NotBoundException;
import javax.swing.JOptionPane;

/**
 *
 * @author Randula
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        passPassword = new javax.swing.JPasswordField();
        lblUserType = new javax.swing.JLabel();
        cmbUserType = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        lblError = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(102, 0, 0));
        lblTitle.setText("Log In....");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, 199, 46));

        lblUserName.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblUserName.setText("User Name");
        getContentPane().add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 141, -1, 34));

        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(102, 0, 0));
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 142, 242, 34));

        lblPassword.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblPassword.setText("Password");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 194, 69, 33));

        passPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passPassword.setForeground(new java.awt.Color(102, 0, 0));
        getContentPane().add(passPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 194, 242, 33));

        lblUserType.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblUserType.setText("User Type");
        getContentPane().add(lblUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 88, 69, 38));

        cmbUserType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbUserType.setForeground(new java.awt.Color(102, 0, 0));
        cmbUserType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Adminstrator", "Telephone Operator", "Chef" }));
        getContentPane().add(cmbUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 88, 242, 38));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 272, 22));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 250, 10));

        jButton2.setText("LOGIN");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 244, 32));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        try {
            String userType = (String)cmbUserType.getSelectedItem();
            String userName = txtUserName.getText();
            String password = String.valueOf(passPassword.getPassword());
            
            UserController userController = ServerConnection.getServerConnector().getUserController();
            User user = userController.getUser(userName);
            
            if(user != null){
                if(user.getPassword().equals(password) && user.getType().equalsIgnoreCase(userType)){
                    if(userType.equalsIgnoreCase("Adminstrator")){
                        new AdminConsol( user.getUserId(),user.getUserName()).setVisible(true);
                    }else if(userType.equalsIgnoreCase("Chef")){
                        new KitchenFrame( user.getUserId(),user.getUserName()).setVisible(true);
                    }else if(userType.equalsIgnoreCase("Telephone Operator")){
                        new TelephoneOperatorFrame(user.getUserId(),user.getUserName()).setVisible(true);
                    }
                    this.dispose();
                }
                
                lblError.setText("We found an error with your user name and password");
                
            }else{
                 JOptionPane.showMessageDialog(this, "Invalid User Name", "Message", 1);
            }
            
            
        } catch (IOException ex) {
             JOptionPane.showMessageDialog(this, "Sever is Currently Disconnected", "Message", 1);
             System.exit(0);
        } catch (NotBoundException ex) {
            JOptionPane.showMessageDialog(this, "Sever is Currently Disconnected", "Message", 1);
             System.exit(0);
        }
        
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbUserType;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserType;
    private javax.swing.JPasswordField passPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
