/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.oms.main;

import edu.ijse.oms.factory.DinamoreFactory;
import edu.ijse.oms.factory.DinamoreFactoryImpl;
import java.io.IOException;
import java.net.InetAddress;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.UnknownHostException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.rmi.server.UnicastRemoteObject;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Randula
 */
public class ServerStart extends javax.swing.JFrame {

    /**
     * Creates new form ServerStart
     */
    private Registry serverRegistry;
    private DinamoreFactory dinamoreFactory;

    public ServerStart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConnection = new javax.swing.JButton();
        lblStime2 = new javax.swing.JLabel();
        lblStartTime = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblCstatus = new javax.swing.JLabel();
        lblEtime = new javax.swing.JLabel();
        lblEndTime = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtServerPane = new javax.swing.JTextArea();
        lblTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConnection.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnConnection.setText("Establish Connection");
        btnConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectionActionPerformed(evt);
            }
        });
        getContentPane().add(btnConnection, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 230, 60));

        lblStime2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblStime2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        getContentPane().add(lblStime2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 150, 30));

        lblStartTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStartTime.setText("Start Time");
        getContentPane().add(lblStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 80, 30));

        lblStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStatus.setText("Status");
        getContentPane().add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 80, 30));

        lblCstatus.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblCstatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        getContentPane().add(lblCstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 150, 30));

        lblEtime.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblEtime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        getContentPane().add(lblEtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 150, 30));

        lblEndTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEndTime.setText("End Time");
        getContentPane().add(lblEndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 80, 30));

        txtServerPane.setEditable(false);
        txtServerPane.setColumns(20);
        txtServerPane.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        txtServerPane.setRows(5);
        jScrollPane1.setViewportView(txtServerPane);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 610, 390));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(102, 0, 0));
        lblTitle.setText("Dinamore Center...");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, 320, 46));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectionActionPerformed

        if (btnConnection.getText().equalsIgnoreCase("Establish Connection")) {
            startServer();
        } else {
            shutDownServer();
        }
    }//GEN-LAST:event_btnConnectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerStart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnection;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCstatus;
    private javax.swing.JLabel lblEndTime;
    private javax.swing.JLabel lblEtime;
    private javax.swing.JLabel lblStartTime;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStime2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtServerPane;
    // End of variables declaration//GEN-END:variables
   private void startServer() {
        try {

            dinamoreFactory = new DinamoreFactoryImpl();
            serverRegistry = LocateRegistry.createRegistry(5050);
            serverRegistry.rebind("Server", dinamoreFactory);
            btnConnection.setText("Disconnect Server");
            txtServerPane.append("Server Started at : " + InetAddress.getLocalHost() + "\n");
        } catch (RemoteException ex) {
            txtServerPane.append(ex.getMessage());
        } catch (java.net.UnknownHostException ex) {
            Logger.getLogger(ServerStart.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ServerStart.class.getName()).log(Level.SEVERE, null, ex);
        }
        DateFormat dateFormat;
        Date date = new Date();
        dateFormat = new SimpleDateFormat("HH:mm:ss");
        lblStime2.setText(dateFormat.format(date));
        lblCstatus.setText("Running...");
    }

    private void shutDownServer() {
        try {
            DateFormat dateFormat;
            Date date = new Date();
            btnConnection.setText("Establish Connection");
            dateFormat = new SimpleDateFormat("HH:mm:ss");
            lblEtime.setText(dateFormat.format(date));
            lblCstatus.setText("Stoped...");
            serverRegistry.unbind("Server");
            UnicastRemoteObject.unexportObject(serverRegistry, true);
            txtServerPane.append("Server Stoped at : " + InetAddress.getLocalHost() + "\n");

        } catch (RemoteException | NotBoundException | java.net.UnknownHostException ex) {
             Logger.getLogger(ServerStart.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
